apiVersion: v2
name: trivy-collector
description: Multi-cluster Trivy report collector and viewer
type: application
deprecated: false
version: 0.6.0
appVersion: "1.4.0"
keywords:
  - trivy
  - security
  - vulnerability
  - sbom
  - kubernetes
home: https://github.com/younsl/o
sources:
  - https://github.com/younsl/o/tree/main/box/kubernetes/trivy-collector
maintainers:
  - name: younsl
    email: cysl@kakao.com
    url: https://github.com/younsl
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Optimize memory usage with lazy JSON loading and reduced page size"
