apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kuo.fullname" . }}
  labels:
    {{- include "kuo.labels" . | nindent 4 }}
rules:
  - apiGroups: ["kuo.io"]
    resources: ["eksupgrades"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kuo.io"]
    resources: ["eksupgrades/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list"]
  - apiGroups: ["karpenter.k8s.aws"]
    resources: ["ec2nodeclasses"]
    verbs: ["get", "list"]
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
