{{- if .Values.slack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuo.fullname" . }}-slack
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuo.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhook-url: {{ .Values.slack.webhookUrl | quote }}
{{- end }}
