{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gss.excludeConfigMapName" . }}
  labels:
    {{- include "gss.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  exclude-repos.txt: |-
    {{- range .Values.excludedRepositoriesList }}
    {{ . | indent 4 }}
    {{- end }}
{{- end }}
