apiVersion: v2
name: kuo
description: Kubernetes Upgrade Operator for EKS clusters
type: application
version: 0.1.1
appVersion: "0.1.0"
maintainers:
  - name: younsl
    url: https://github.com/younsl
