{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trivy-collector.fullname" . }}
  labels:
    {{- include "trivy-collector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "trivy-collector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "trivy-collector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
