{{- if and (eq .Values.mode "server") .Values.server.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.server.gateway.name | default (include "trivy-collector.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-collector.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.server.gateway.parentRefs }}
    - name: {{ .name }}
      {{- if .group }}
      group: {{ .group }}
      {{- end }}
      {{- if .kind }}
      kind: {{ .kind }}
      {{- end }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
    {{- end }}
  {{- if .Values.server.gateway.hostnames }}
  hostnames:
    {{- range .Values.server.gateway.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.server.gateway.rules }}
    - matches:
        {{- range .matches }}
        - path:
            type: {{ .path.type }}
            value: {{ .path.value }}
        {{- end }}
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        {{- range .backendRefs }}
        - name: {{ .name | default (include "trivy-collector.fullname" $) }}
          port: {{ .port | default $.Values.service.port }}
        {{- end }}
    {{- end }}
{{- end }}
