{{- if and (eq .Values.mode "server") .Values.server.persistence.enabled (not .Values.server.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trivy-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivy-collector.labels" . | nindent 4 }}
    {{- with .Values.server.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.server.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.server.persistence.accessMode }}
  {{- if .Values.server.persistence.storageClass }}
  storageClassName: {{ .Values.server.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
{{- end }}
